[package]
name = "mini-groth16"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
regex = "1.11.1"
rand = "0.8.5"
ark-serialize = "0.5.0"
serde_json = "1.0.140"
